### ISSUE TITLE
Roadmaps

### ISSUE THREAD

**Issue by dhirajanand014** [Gaspard-Bruno/react-native-infinite-swiper#1]
What are the future roadmaps?

**Comment by jpamarohorta** [comment]
Hello, we recently added a tiny [Roadmap](https://github.com/Gaspard-Bruno/react-native-infinite-swiper#roadmap) section to the README and published today version 3.1.1 with some new improvements like:
- Swipe to close zoom modal
- Press to open zoom modal

Do you have any suggestion for features that could be interesting in the Roadmap?
